### ISSUE TITLE
Volunteer meet 14 June

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#100]
## MoM

- Follow up #95
    - Announcement automation, no work was done.
    - @piratesparsh, any updates from Amity's side?
    - #52 talk speaker needed. Send CFP today.
    - Complain bot #97 . No progress
    - #78 ilugd collab
        - 28st date is finalized
        - Finalize workflow in next call
        - ILUGD/talks#176 and #101 to be scheduled.
- #102 How to hand off give-aways.
    - @smitjethwa Python challenge, maybe a week long thing? Anyone who finishes it gets a goodie.
    - Exploring nltk/spacy/requests for a week. @smitjethwa let participants decide their own libraries.
    - Think of methods to actually distribute the goodies.
    - How to stop people from choosing trivial libraries.
- Soa ML track
    - Let's integrate https://github.com/kabirnagpal/100DaysofML into an "ML beginners" track?
    - Add 100DaysOfML to community collaborators in pyjaipur
    - After the tracks people can compete online and receive goodies from the community for merit.
    - Further collaborations with kaggle/AV?
- HydPy initiated contact to try and collaborate on some event. Will update once more info is there.
- Ask Anuj about the collab email with IncubateInd. Let's go ahead since poll in group resulted in 62% in favour. 

## Adgenda

- Follow up on #95
- Ilugd collab talk proposals
    - https://github.com/ILUGD/talks/issues/176
    - `Cool can you also comment on the above issue so that speaker also knows what is final !!`
- How to handle give-aways
    - Give aways for community generated content on youtube/medium etc
- Soa development
    - ML track from what @kabirnagpal mentioned in the TG group.

## Checklist

- [x] Google calendar event on pyj calendar
    - [x] Add announce message
    - [x] Create a meeting link using meet.google or jitsi
- [x] pyjaipur.org
    - [x] Google calendar link
    - [x] Call link from calendar
- [x] meetup
    - [x] Create draft for event
    - [x] Add poster
    - [x] Add announce message
    - [x] Publish but DONT announce
- [x] telegram
    - [x] Event poster 
    - [x] Quick details
    - [x] Link to calendar event

**Comment by anchal7299** [comment]
I want to give talk on this topic #101, but I have some network issues. If anyone could co- present on this topic please mention your name.

**Comment by theSage21** [comment]
# MoM

- Follow up #95
    - Announcement automation, no work was done.
    - @piratesparsh, any updates from Amity's side?
    - #52 talk speaker needed. Send CFP today.
    - Complain bot #97 . No progress
    - #78 ilugd collab
        - 28st date is finalized
        - Finalize workflow in next call
        - ILUGD/talks#176 and #101 to be scheduled.
