### ISSUE TITLE
Python coding challenge give aways

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#102]
@smitjethwa and @shvamabps jab time mile yahan comment kardoge?

1. How to go do this event?
2. When to start?

- [ ] @theSage21 Framework for setting up the contest and hosting on our site
- [ ] @shvamabps @smitjethwa formulate questions for the first challenge.

**Comment by smitjethwa** [comment]
Yes!

**Comment by smitjethwa** [comment]
We can go ahead with the following libs
- requests
- nltk
- flask
- pandas / numpy
- mayplotlib / seaborn

**Comment by theSage21** [comment]
Discussed with @shvamabps :

## Challenge overview

- Challenge is run weekly. Each week there is one winner.
- Announced on Monday/Sunday night
- Challenge runs until a winner is declared. Then the next challenge is issued.
- Max of 5 steps in a challenge.
- Use time taken during attempts to break ties.

## Reference links

- Provide a REPL to people who attempt this challenge:
    - https://training.ilugc.in/
    - https://www.pythonanywhere.com/
    - https://repl.it/

**Comment by shvamabps** [comment]
We'll start with **re**

**Comment by theSage21** [comment]
@smitjethwa if you're online ping in the TG group. We're on a call right now for this.

**Comment by smitjethwa** [comment]
Hey, 
I clicked on _unassign me_ accidentally. Please add me again,

**Comment by shvamabps** [comment]
# Regular Expression Questions

- Check whether a string starts and ends with a same character or not.
- Remove duplicate words from the sentence using `regex`
- Validate your email address using `regex`
- Extract the keywords of the text searched in an url using `regex`.
- Determine whether the url is valid or not using `regex`.
- Validate that the mobile number provided is correct or not based on the rules that number of digits that a particular mobile number should have. (Eg: In India the mobile number has 10 digits so write a regex for validating that number.)

**Comment by theSage21** [comment]
Let's create a new issue for this and post the questions there. We'll create a new project for this and follow progress there.

People can open PRs to submit answers.

@shvamabps ye kar doge please? Let me know if you don't have enough access.
