### ISSUE TITLE
A talk on Scrappy and BeautifulSoup (framework and a library)

### ISSUE THREAD

**Issue by The-Nightwing** [PyJaipur/PyJaipur#106]
Please include the following when writing about a talk / workshop:

- This would be an online workshop, students will be having their laptops.
- Web-Scrapping techniques will be covered showing an example, and then giving a small assignment to practice the same.

**Comment by theSage21** [comment]
Hi @The-Nightwing 

Could you add a few details about how long this would be?

In case you have slides/code ready please link to those as well so that we can decide when to schedule this talk on this Sundays call #103

**Comment by The-Nightwing** [comment]
Hi Arjoon,
I was thinking that it could be of 20 mins, just give the students an idea of what scrappy is and Beautiful Soup. I can't make slides on it, although I'll try finding one on the internet.
RegardsShivam VermaThe-NightWing

**Comment by theSage21** [comment]
@The-Nightwing in that case, could you post relevant links to code/resources here?

**Comment by The-Nightwing** [comment]
I found one pretty good resource for scrapy: https://www.pythongasm.com/introduction-to-scrapy/
Some codes(mine): https://drive.google.com/drive/folders/1ShEbyeyJ8c7k04ZjKqoUOPEsA406phly?usp=sharing

**Comment by theSage21** [comment]
Could you please put that code on github somewhere?

**Comment by The-Nightwing** [comment]
Sure.

**Comment by The-Nightwing** [comment]
https://github.com/The-Nightwing/Scarpy-Preview

This is code is for scraping a shopping website and create a CSV with scraped data using pandas library.

**Comment by The-Nightwing** [comment]
Is this issue still active?

**Comment by The-Nightwing** [comment]
Please Reply.

**Comment by theSage21** [comment]
We can add it as a topic of discussion to our next volunteer meet #119

**Comment by The-Nightwing** [comment]
Thanks
