### ISSUE TITLE
A talk on APIs (Application Programming Interfaces)

### ISSUE THREAD

**Issue by jjay075** [PyJaipur/PyJaipur#113]
Please include the following when writing about a talk / workshop:

- What is APIs? Why do we use?
- How does it work?
- Using API a demo/ idea to build your own COVID-19 tracker website in flask.
- At last, share some resources where you can find public and private APIs.
- participants bring a laptop if they want.

**Comment by theSage21** [comment]
@jjay075 this is scheduled for 27 June :+1:
