### ISSUE TITLE
Animating SVGs

### ISSUE THREAD

**Issue by rishabhKalakoti** [PyJaipur/PyJaipur#12]
An introduction to adding basic animations to web pages with Scalable Vector Graphics.

**Pre-requisites**
- Basic JavaScript and DOM
- Basic CSS 3 animations

**Expected duration**

_20-30 minutes_

**Level**

_Beginner_

**Resources**

[links](https://github.com/rishabhKalakoti/session-notes/tree/master/svg)

**Speaker Bio**

Hey. I am Rishabh. Final year B.Tech student. Have tried my hands at a few things. Planning to share with the community the ones I found interesting.

**Comment by theSage21** [comment]
NOTE: Material has been provided at https://github.com/rishabhKalakoti/session-notes/tree/master/svg and the top comment has been updated to reflect this.
