### ISSUE TITLE
Regular expression questions

### ISSUE THREAD

**Issue by shvamabps** [PyJaipur/PyJaipur#126]
## Solve at least 3 of these to get the prize

  *  Check whether a string starts and ends with a same character or not.
  *  Remove duplicate words from the sentence .
  *  Validate your email address .
  *  Extract the keywords of the text searched in an url.
  *  Determine whether the url is valid or not.
  *  Validate that the mobile number provided is correct or not based on the rules that the number of digits that a particular mobile number should have. (Eg: In India the mobile number has 10 digits so write a regex for validating that number.)

**Comment by shvamabps** [comment]
@theSage21  kindly review this!!

**Comment by theSage21** [comment]
Sahi hai. I've added a few more points about how to participate in #128

**Comment by theSage21** [comment]
@piyushagarwal08 ka attempt accept karte hain! Congratulations! :tada:
