### ISSUE TITLE
Community call : 6 Sept 2020

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#149]
## Agenda

- Follow up on #146

**Comment by Shivank98** [comment]
I was talking to some folks of Kota coachings. at the time of JEE/NEET, they usually have to do some manual tasks of fetching the results manually, I thought to automate did and have a basic selenium script. was thinking if we over a community call can discuss over that to make it more efficient.

**Comment by theSage21** [comment]
@Shivank98 sounds good. Any chance we could invite one of them to the call?

**Comment by Shivank98** [comment]
I ll try.
