### ISSUE TITLE
Python workload in Azure

### ISSUE THREAD

**Issue by karthikeyanVK** [PyJaipur/PyJaipur#151]
Please include the following when writing about a talk/workshop:

- 2-3 sentence description of the talk/workshop.

You can learn about the various offering available in azure for the python-based worked loads. You will learn through the demo on how you can deploy your code in the web app and also docker application in azure.

- Do participants need to bring a laptop? - No

**Comment by randomizemuj** [comment]
![Poster](https://user-images.githubusercontent.com/45651729/92732804-92b0ef80-f394-11ea-9e9e-4683ca012210.jpg)
Date: 13th September '20
Timing: 9 PM

Python Workload in Azure", by one of the pre-eminent Microsoft MVP's of our country, Mr.Karthikeyan V K. 


About: With over 3 MVP awards, he is an expert 😎 in building highly scalable solutions with ☁️ cloud-native architecture and also has a huge experience in reducing your cloud cost💵.He conducts various workshops & Bootcamp on Microservices and DevOps.


Get in the cutting edge of python workload with hands on experience🧑‍💻👩‍💻 in deploying your code in the web app and docker applications in azure withal.

[Meetup Link](www.pyjaipur.org/#call)

**Comment by theSage21** [comment]
The speaker can be contacted at `@karthik3030` on twitter.
