### ISSUE TITLE
Automation with python,docker,aws

### ISSUE THREAD

**Issue by anchal7299** [PyJaipur/PyJaipur#16]
**Abstract**

- Deploying docker containes on AWS machines to run python programs easily.

**Pre-requisites**

- Python3 basics 

**Expected duration**
 
_Time that your talk/workshop would take - _
   30 minutes

**Level**

_Beginner_

**Resources**

_Resources will be add soon_

**Comment by theSage21** [comment]
I'll tag this issue once you edit the top comment with the relevant details

**Comment by theSage21** [comment]
@anchal7299 in case any slides/etc were not included in #17 please open a new PR  for those materials.

**Comment by anchal7299** [comment]
> @anchal7299 in case any slides/etc were not included in #17 please open a new PR for those materials. I'll be closing this issue since the event is done.

ok
