### ISSUE TITLE
Amity University Rajasthan

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#22]
Email received at pyjaipur.india@gmail.com
```
Hello,

Greetings from Team Code N Run!

 

We take the honor to announce the Code N Run getting hosted at The Amity University Rajasthan, Jaipur, from 28th february 2019 12 am to 29th February 2019 at 1 pm in its techno-cultural fest ODYSSEY'2020.

 

We are writing to you concerning a sponsorship opportunity with Code N Run.

 

Code N Run is a 24-hour long event with a vision to provide hands-on experience in the field of Technologies and Ideas. It's a 24-hours event where developers come together to share ideas, make teams, build projects, and show their creativity!

 

A Codeathon is a design sprint-like event, in which computer programmers and others involved in software development, including graphic designers, interface designers, project managers, domain experts, and others collaborate intensively on software projects.

 

Here is what happens at Code n Run:
1: Meet, Pitch and Team Up
2: Learn & Work
3: Present and Celebrate

You are our first reach as a monetary sponsor and we hope for a positive response. If your organization would like to participate in this year’s event as a sponsor, please contact us. Thank you for your time and consideration, and we look forward to hearing from you

Sincerely,

Team Code n Run
```

**Comment by theSage21** [comment]
Hi @honeyakshat999

PyJaipur does not sponsor events.
If you would like our support for other things please let us know.

**Comment by honeyakshat999** [comment]
sir,
 We want promotions (telegram group ,meetup group),swags for participants,mentorship and judging.

**Comment by theSage21** [comment]
- I think we can put one short text message in the Telegram group, and perhaps mention something on the pyjaipur website?
- As for the mentorship and judging we can mention it in [tomrorrow's meetup](https://www.meetup.com/PyJaipur/events/jgkqnrybcdbdc/) and if any members are interested they can reply on this issue. It would be nice if you attend tomorrow and present your event yourself and try to convince people:smile: 
- Sadly PyJaipur swag is only for events hosted by PyJaipur directly so I don't think we'll be able to hand those out.

**Comment by honeyakshat999** [comment]
Are mentors and judges are confirmed?
Is social media promotions are confirmed?

**Comment by theSage21** [comment]
- For mentoring and judging I don't think anyone has been able to clear their schedule yet
- We can mention the event's link in the pyjaipur links group in case you have not already put it there.
