### ISSUE TITLE
Automizing Data Extraction using Web-Scraping

### ISSUE THREAD

**Issue by ayushisaxena22050** [PyJaipur/PyJaipur#25]
Abstract:
 1. Web-Scraping Introduction
 2. Scraping Data from website using BeautifulSoup
Pre-requisites:
 Basic python
 Python3 installed in your laptop.
 Jupyter Notebook installed.

Expected duration:
 Time that your talk/workshop would take - _
 45 minutes

Level:
Beginner

Resources
https://www.crummy.com/software/BeautifulSoup/bs4/doc/ption of the talk/workshop.

**Comment by theSage21** [comment]
https://github.com/ayushisaxena22050/WebScrapping-of-Indeed-website

**Comment by theSage21** [comment]
https://github.com/PyJaipur/web-scrape

**Comment by theSage21** [comment]
https://github.com/PyJaipur/SoA
