### ISSUE TITLE
suggestions are required for template of monthly letter.

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJaipur#27]
Please have a look at [this](https://github.com/PyJaipur/PyJaipur/blob/master/templates/emails/monthly.txt) and suggest your inputs.
This is a template for monthly letter that we are planning to post from this month.

**Comment by theSage21** [comment]
This looks good. :+1: 

1. Do we need date and time for previous events? A link to meetup page /resources/recordings should be enough?

**Comment by Shivank98** [comment]
Hmm. yeah, date and time we can remove for previous events.

**Comment by Shivank98** [comment]
please have a look again at the file.

**Comment by theSage21** [comment]
@Shivank98 you can make these changes in a separate branch and open a pull request. That way it's easier to review before putting things in master.
