### ISSUE TITLE
Requesting a call on fundamentals of Linux

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJaipur#33]
I want to request a call on the fundamentals of Linux. 
* Basic and useful commands. 
* Shells/Terminals etc
* How does virtual environments works and using them.
* What you can do with editors like VIM.

The reason behind the request is that many times I feel that I am not using all things that are available.

You can also share some resources also in comments but a call is preferred.

**Comment by theSage21** [comment]
I can do the terminals + vim part.

How about this weekend?

**Comment by Shivank98** [comment]
Sounds cool. Thanks
