### ISSUE TITLE
Serverless 

### ISSUE THREAD

**Issue by heyAyushh** [PyJaipur/PyJaipur#4]
I take pride in proposing the talk for Serverless Azure function, Providing some basic insights into serverless world, what is it? , What is there for us? , and How can we get started easily.

**Comment by theSage21** [comment]
Hi @heyAyushh ,

Is this still valid?

If you already have slides/github/talking points please post them here and we can figure out which meetup to present this talk in.

**Comment by theSage21** [comment]
@heyAyushh please feel free to open this again if you want to give this talk again.
