### ISSUE TITLE
How to run website?

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJaipur#48]
I am sure there would be a way to run all whole website together instead of opening each HTML file separately.
It's Jinja template but I couldn't find any .py file. I tried to run it using bottle like `return template('src/index.html', baseurl='')` but that also didn't work.

**Comment by theSage21** [comment]
Samjha nahi mai. `make web` already runs the full site. What are you trying to do?

**Comment by Shivank98** [comment]
Thia is pyjaipur website. not SoA

**Comment by theSage21** [comment]
My god. So sorry.

After installing requirements you can run `python -m staticsite build` to
build the site.

The site is build into the target folder and can be served using `python -m
http.server`.

If you're doing live development use `python -m staticsite watch` and the
site will be automatically rebuilt every time you write changes to your
source files and the browser page will be refreshed.

See https://github.com/theSage21/staticsite for code details.

**Comment by Shivank98** [comment]
looks like I don't have access rights to repo you shared.
