### ISSUE TITLE
Web automation

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#54]
Time Duration: 45 ~ 60  minutes
Topics to be covered:
1. What is Automation and RPA?
2. RPA vs normal automation (probably using Selenium a quick go through) ~> basically why I insist  over RPA when we talk about automation
   The important difference that I want to show is the term "low code / No code"
3.  Few Bot Examples:
     1~> Table data scrapping (can be made during presentation 3-4 minutes): Structured Data
     2 ~> Pattern Based Data Scrapping (can be made during presentation  3-4 minutes ): Semi-Structured Data
     3 ~> LinkedIn Profile Scrapper(Live Running Demo) : Unstructured Data
4. Installation Guide and how to start journey with RPA
These are the few points that came to my mind, would like to know suggestions as how it can be done within time,  I believe all this might not be possible within hour, and want to know if

**Comment by HeroicHitesh** [comment]
I am interested in working on automation but need guidance.

**Comment by theSage21** [comment]
@HeroicHitesh this issue was for a talk on web automation that @piyushagarwal08 had mentioned in the group I think. Maybe you could work with him to write up this talk? I can help once you have a basic PR outlining the talk opened.

**Comment by piyushagarwal08** [comment]
Sorry! due to current work I had completely forgotten about this
Time Duration: 45 ~ 60  minutes
Topics to be covered:
1. What is Automation and RPA?
2. RPA vs normal automation (probably using Selenium a quick go through) ~> basically why I insist  over RPA when we talk about automation
3.  Few Bot Examples:
     1~> Table data scrapping (can be made during presentation 3-4 minutes): Structured Data
     2 ~> Pattern Based Data Scrapping (can be made during presentation  3-4 minutes ): Semi-Structured Data
     3 ~> LinkedIn Profile Scrapper(Live Running Demo) : Unstructured Data
4. Installation Guide and how to start journey with RPA
These are the few points that came to my mind, would like to know suggestions as how it can be done within time,  I believe all this might not be possible within hour, and want to know if

**Comment by HeroicHitesh** [comment]
> @HeroicHitesh this issue was for a talk on web automation that @piyushagarwal08 had mentioned in the group I think. Maybe you could work with him to write up this talk? I can help once you have a basic PR outlining the talk opened.

@theSage21 Ohhk. Actually I am new to automation stuff, so, I thought that I would learn something by doing some tasks. But I have no prior experience so I guess @piyushagarwal08 will have to do this by himself😅 although this talk will be helpful for me to learn about web automation, so, looking forward to it.
@piyushagarwal08 if you can recommend some good resources to learn RPA from maybe I can learn before the talk is organised and help you out with the talk.

**Comment by piyushagarwal08** [comment]
academy.uipath.com
university.automationanywhere.com

You can ping me on mail piyushagarwal.0108@gmail.com
I can share my zoom id.. using which today evening you can attend my session over the same @5pm

**Comment by HeroicHitesh** [comment]
Sorry for the delayed reply, actually I had an internship exam yesterday. This is the reason why I wasn't able to attend your session also.
Thanks for the resources I'll get started with it right away.

**Comment by theSage21** [comment]
@piyushagarwal08 can we schedule this talk for the June meetup? It should be on 27 June

**Comment by piyushagarwal08** [comment]
Cool

**Comment by theSage21** [comment]
@piyushagarwal08 this talk is scheduled for 27 June. If you have the slides/code ready could you please upload them here.

**Comment by theSage21** [comment]
@piyushagarwal08 could you please confirm if you'll be taking this talk on 27th June?

**Comment by piyushagarwal08** [comment]
Yes,
Tomorrow I have an event so after that I will share the ppt
Agenda is same as mentioned over GitHub

**Comment by piyushagarwal08** [comment]
Bhaiya, I can talk about RPA and how to do automate web applications using
that but I don't have any specific presentation ready for that.
Will it be ok if we do it practically like normal talk and answering
through demonstration with things regards to web Automation.

**Comment by theSage21** [comment]
Should be fine to do that. Just make sure that whatever code/links you use in demos are listed here or in some other repo.

**Comment by piyushagarwal08** [comment]
There is no code or link 😅.. its just drag and drop and files work only
with specific software
