### ISSUE TITLE
Organizing meetup

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#7]
Hi

We will be having a general meetup regarding the activities of PyJaipur.

- 11:00 - 14:00 hrs on Jan 5 2020.
- [Venue is Forsk labs, Sitapura, Jaipur](https://g.page/forsklabs?share)

## Agenda

- ~[ ] Clear backlog from previous events~ Could not be discussed due to absent members
- [x] Promotional links and a bot for them
- [x] Monthly meetup schedule
- [x] Talks schedule
- [x] Projects / Sponsorship / Activities

Please react to this comment with a rocket emoji to indicate your presence :rocket:

**Comment by rishabhKalakoti** [comment]
Looking forward to it :)

**Comment by sakshamtaneja21** [comment]
looking forward to it

**Comment by Avinashx** [comment]
Yup.

**Comment by theSage21** [comment]
Let's just use the rocket emoji to mean that someone will be attending.

**Comment by theSage21** [comment]
Let's assemble at Forsk labs in Sitapura. They've been supportive of PyJaipur so far and it would be nice to start the new year with them :smile: 

https://g.page/forsklabs?share

**Comment by MANISH-CHOUHAN** [comment]
Yup☀️

**Comment by theSage21** [comment]
Timings available for us are 1100 hrs to 1400 hrs. Please be in the venue at 1100 hrs. I'll meet everyone there.

**Comment by sandeepjain20178** [comment]
yes

**Comment by AdityaSharma07082000** [comment]
👍

**Comment by theSage21** [comment]
I'll see you all at 11 AM tomorrow :smile:

**Comment by theSage21** [comment]
Attended: @theSage21, @rishabhKalakoti, Anchal Agarwal, Surender, Sylvester

Discussed and finalized:

1. Monthly meetups will be held regularly. Bi-weekly local member meetups will be remote/online
2. PyJaipur's participation in CodeNBuild might be questionable since our role there is not clear. See #9 for event details.
3. Community learning tracks need to be finalized. Potential candidates
    - Web development
    - Data science
4. Calculate group churn
5. Open source projects built by the PyJaipur community. Perhaps contribute to other communities (https://github.com/pythonindia/junction is a good candidate)

Please let me know if I missed something.
