### ISSUE TITLE
Website appears to overflow on bigger screens

### ISSUE THREAD

**Issue by Jithinqw** [PyJaipur/PyJaipur#70]
<img width="1680" alt="Screenshot 2020-05-15 at 2 28 30 PM" src="https://user-images.githubusercontent.com/20675707/82032262-97041f00-96b8-11ea-864b-0fd2dfb8647c.png">

**Comment by theSage21** [comment]
This is strange. Thanks for bringing it up :+1: My screen seems to display it fine.
![image](https://user-images.githubusercontent.com/7693265/82044704-772a2680-96cb-11ea-8e9f-7a86537d7db2.png)

Could you share a few details to help me debug?

- What browser?
- OS
- screen resolution
- zoom level?

**Comment by theSage21** [comment]
woah! the color is different. :thinking: veeeery strange.

**Comment by Jithinqw** [comment]
The website loaded on Chrome and Safari, had the same effect.

OS: Mac OSX  Catalina 
Screen: 15.4 inch 2880*1800

**Comment by Jithinqw** [comment]
Try to reduce the space from left. It feels everything is congested to right.

**Comment by theSage21** [comment]
I think I'll just move this code to a grid. That way I don't have to worry about a lot of things :D

**Comment by theSage21** [comment]
@Jithinqw does the site look ok now on your browser?

https://deploy-preview-77--tender-jang-4fceb8.netlify.app/

**Comment by Jithinqw** [comment]
Perfect
