### ISSUE TITLE
ilugd collab

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#78]
Collaboration with Ilug-d for some talks/workshops?

1. propose collab to ilug-d. 23 May - 27 June some weekend.
2. on acceptance send out call for speakers in pyj
3. go listen to collab talk.

# Todo

- [x] 28 June 1630 : 1900 hrs
- [x] @thesage21 send out cfp for representing pyj in ilugd collab. 1 speaker slot available.
- ~~[ ] Find supporting speaker for #101~~
- [x] Ilugd will present ILUGD/talks#176

**Comment by theSage21** [comment]
Proposed message:

We'll be collaborating with [India Linux Users Group Delhi](https://www.linuxdelhi.org/) this month.

There will be two talks. One speaker will be from their end and one speaker will be from PyJaipur.
This event will be broadcast on both PyJaipur and ILUG-D social platforms.

Anyone who would like to represent PyJaipur for this collaboration is welcome to post a message here or on [github issue #78](https://github.com/PyJaipur/PyJaipur/issues/78) .
You'll receive help from the entire community for preparing your talk if you need it so go and propose a talk!

Ladies are especially encouraged to participate in this event!

**Comment by ayushisaxena22050** [comment]
Yes ..!!
This sounds great.
Are you talking about monthly meetup context?
For the topic part and ladies participations part I have few suggestions:

1.we may ask Preeti  for a talk as she is doing some good work in pytorch
and deep learning.

2. I can prepare a talk myself on Flask framework.

3. I know someone who is interested to give a talk but do it necessarily be
on python related topics.

**Comment by theSage21** [comment]
This would be separate from the monthly meetup.

1. That would be wonderful! If she's interested she can open a [talk proposal](https://github.com/PyJaipur/PyJaipur/issues/new?assignees=&labels=talk&template=talk.md&title=) issue in this project.
2. That would also be wonderful! Go ahead and open a [talk proposal](https://github.com/PyJaipur/PyJaipur/issues/new?assignees=&labels=talk&template=talk.md&title=)
3. Please go ahead and ask them to open a [talk proposal](https://github.com/PyJaipur/PyJaipur/issues/new?assignees=&labels=talk&template=talk.md&title=). The final selection would be done based on what ilugd chooses. We would not want both speakers to speak about the same topic :sweat_smile: .

**Comment by ayushisaxena22050** [comment]
Ok I'll ask them then.
Is there any tentative date for it.

**Comment by theSage21** [comment]
Tentatively 20-21 June

**Comment by theSage21** [comment]
This is now scheduled for 28th June. We'll be going ahead with #101 from our side.

**Comment by theSage21** [comment]
Event link at: https://www.youtube.com/watch?v=X6xlcdbEM04
