### ISSUE TITLE
rules for links in to group

### ISSUE THREAD

**Issue by seema1711** [PyJaipur/PyJaipur#79]

**Comment by Shivank98** [comment]
1. Promotional and Referral link should be banned in chat group.

2. If link is of any non profit communities which are run by volunteers can be posted in group and even can be pinned few hours before event so talk/session can do benefit to all.

3. If a community/org is not run by volunteers but still someone from there side request admins to let him post link related to event, that should be considered. It shows user is not just there for spamming.

**Comment by theSage21** [comment]
I just realized that telegram has a "channel" thing. We could create a PyJ channel and use that to announce things. Channels can have groups linked to them for discussions. That way, announcements don't clutter normal discussions.

**Comment by theSage21** [comment]
@anushajain19 to write up the link group rules + dontasktoask.com link for tg group description.

**Comment by theSage21** [comment]
@nk521 if the join bot is being made, let's make it global so that other communities can use.

**Comment by theSage21** [comment]
I've updated the shieldy message for the group with clear instructions about the pyjaipurlinks group.
