### ISSUE TITLE
Mentor certificates from <= 2019

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#8]
Please comment here and let us know if you haven't received certificates which you were supposed to receive before or during 2019.

## Pending certificates reported

- [ ] NerdNinja
- [ ] Kumaraskanda B B

**Comment by theSage21** [comment]
*Note* @theSage21 someone called @nerdninja on telegram has claimed that they have not received their certificate. Investigate and resolve

**Comment by Shivank98** [comment]
Are we doing something on it? or we can close it?

**Comment by NerdNinja** [comment]
Hi folks. I can't remember what issue started this or when I raised it.

Have you found this through a ticket-management system, or an old
email-trail?

**Comment by theSage21** [comment]
Hi @NerdNinja ,

I think this happened because of a namespace clash. There's a different NerdNinja on our telegram group and you were accidentally tagged because of that username here. Please feel free to unfollow this thread.

Sorry for the trouble.

**Comment by theSage21** [comment]
> Are we doing something on it? or we can close it?

I'm not sure what we can do. I haven't found the time to go through the archives and figure out who needs what.

**Comment by Shivank98** [comment]
Hmm, I suggest as there are no mails who are asking for it. we can close it.

**Comment by theSage21** [comment]
Closed due to inactivity and lack of ability to mitigate. Will reopen if a way is found to recreate mentor certificates.
