### ISSUE TITLE
How to manage topics in to group? Should we use a different platform?

### ISSUE THREAD

**Issue by seema1711** [PyJaipur/PyJaipur#80]

**Comment by seema1711** [comment]
Discord is good.

**Comment by Shivank98** [comment]
I don't usually see a problem where we need channels for topics(like slack). 
We don't really try to look for old chat references for a new query and even if do that TG search is enough.

**Comment by theSage21** [comment]
Agreed. So far dedicated github issues have been good enough for managing topic discussions like the one for jobs.

**Comment by theSage21** [comment]
Please close if no resolution is found in net meetup.
