### ISSUE TITLE
Search telegram group history for topics.

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#81]

**Comment by theSage21** [comment]
1. We need discoverability for our group history so that people can find topics that they missed
2. Maybe use topic modeling to discover topics

**Comment by Shivank98** [comment]
We don't need this.
TG already have a search option. 
if something nice comes which admins find interesting to have or mark #topic_name can be used.

**Comment by theSage21** [comment]
Agreed. Maybe we can keep this open so that we don't forget that it was talked about. Otherwise until this becomes an actual problem we can put this on hold.

**Comment by theSage21** [comment]
duplicate of #80
