### ISSUE TITLE
Volunteer meetup

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#87]
## Announcement message

    We're having a #volunteer meetup this Sunday 9PM!
    Use pyjaipur.org/#call to join the event
    #pyjaipur #event

## Announcement poster
![volunteer_meet](https://user-images.githubusercontent.com/7693265/82821352-9130e980-9ec1-11ea-94ab-f800a50d74c3.jpeg)

## Checklist

- [x] Add announcement message on this issue
- [x] Google calendar event on pyj calendar
    - [x] Add announce message
    - [x] Create a meeting link using meet.google or jitsi
- [x] pyjaipur.org
    - [x] Date and time of starting
    - [x] Short description
    - [x] Google calendar link
    - [x] Call link from calendar
    - [x] Github link if applicable
- [x] Make event poster.
- [x] Update relevant talk/management issues.
- [x] meetup
    - [x] Create draft for event
    - [x] Add poster
    - [x] Add announce message
    - [x] Publish and announce
- [x] linkedin
    - [x] Create event
    - [x] Add poster
    - [x] Add announce message
- [x] twitter
    - [x] Add poster
    - [x] Quick details
    - [x] Link to calendar event
    - [x] Link to call
- [x] telegram
    - [x] Event poster 
    - [x] Quick details
    - [x] Link to calendar event
    - [ ] Announce on:
        - [x] pyjaipur
        - [ ] ilugd
- [x] mailing list
    - [x] Add poster
    - [x] Add announce message
    - [x] Link to calendar event
    - [ ] Announce on:
        - [x] pyj
        - [ ] ilugd
- [x] youtube
    - [x] Create a live stream event
    - [x] Add poster
    - [x] Add announce message

**Comment by Shivank98** [comment]
I 'll put it on mailing list on Saturday. people forget mail.

**Comment by Shivank98** [comment]
# Agenda
- next meetup. talks to host
 - Web Automation by Piyush
 - What does CS means reserved for Amity talk( or talk with much number of attendees)\
 - SOLID Principals, might need a backup speaker. if you are interested you can comment here. https://github.com/PyJaipur/PyJaipur/issues/52

- ilugd collab. How to do this?
- Dates are being decided. after that a call for speaker would be sent. 
- automate social platforms
 - Automatic announcements using API(s)

- dabeaz course on soa? "YES" 
 - https://github.com/PyJaipur/SoA/issues/39

- links rule. Where to put it? Tg group description?
    - updated issue https://github.com/PyJaipur/PyJaipur/issues/79
- dontasktoask link on pyj website ? Where all to put this link? TG group? Put it in Group description. 
    - part of https://github.com/PyJaipur/PyJaipur/issues/79

- Create event entries for June meetup

 Also discussed. 
  - Push Notifications
  -
