### ISSUE TITLE
About CodeNBuild

### ISSUE THREAD

**Issue by sakshamtaneja21** [PyJaipur/PyJaipur#9]
This issue is for the CodeNBuild hackathon taking place on 25th Jan. 

Details can be found in #10

**Comment by theSage21** [comment]
@sakshamtaneja21 beautiful work :+1: I'll put this in a PR soon and have this issue re-formatted for discussions.

**Comment by theSage21** [comment]
Closing due to unresponsiveness and event date being in the past.
