### ISSUE TITLE
Volunteer meet - 7 June 2020

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJaipur#95]
# Agenda

- Follow up on #87
- Shieldy replacement

**Comment by theSage21** [comment]
- shieldy replacement discussions will be held under #97

**Comment by Shivank98** [comment]
MOM:
Announcement automation has been done for Twitter and google calendar.  Meetup.com API has been approved. LinkedIn post can be made using a personal account but not the company's account.

Amity talk has is on hold as there is no response from Sparsh.

Talks on SOLID and WEB AUTOMATION has been fixed. though a backup speaker is still needed for SOLID Principals. need to send a CFP

following #79 a complaint bot is started which need to be improved for all community. 
#97 how to complain about harassment anonymous. 

ILUGD dates still need to be decided.  A CFP also needs to be sent from PyJ.
